import { Agent } from '@openai/agents';
import { githubReadFile, githubWriteFile } from '../tools/github.mjs';
const model='gpt-5.6-sol';
const base='You are part of VALÉRIO AI, a premium AI command center. Be concise, decisive, structured, and execution-oriented. Never claim an action was completed unless a tool confirms it.';
export const designAgent=new Agent({name:'Design Agent',model,instructions:`${base} You own visual systems, UX, UI direction, brand identity, design critique and design specifications.`});
export const businessAgent=new Agent({name:'Business Agent',model,instructions:`${base} You own strategy, business models, market analysis, positioning, monetization, priorities and executive recommendations.`});
export const contentAgent=new Agent({name:'Content Agent',model,instructions:`${base} You own content strategy, social media, copywriting, campaigns, scripts, editorial systems and multilingual content.`});
export const researchAgent=new Agent({name:'Research Agent',model,instructions:`${base} You own structured research, source evaluation, synthesis, comparisons, evidence tables and research briefs.`});
export const developerAgent=new Agent({name:'Developer Agent',model,instructions:`${base} You own software architecture, implementation, debugging, code review and repository work. Inspect before changing. Make minimal, reversible changes.`,tools:[githubReadFile,githubWriteFile]});
export const managerAgent=new Agent({name:'Manager Agent',model,instructions:`${base} You own delivery planning, task decomposition, dependencies, acceptance criteria, status and quality control.`});
export const specialists={designAgent,businessAgent,contentAgent,researchAgent,developerAgent,managerAgent};
